# Change these first
owner: lucasboh # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: Livieres Guggiari
    url: https://livieresg.com.py
    maxResponseTime: 7000
  - name: Sunshine Lettering
    url: https://sunshineletteringpy.com
    maxResponseTime: 7000
  - name: Estudio TFZ
    url: https://estudiotfz.com
    maxResponseTime: 7000
  - name: Allinea Pilates
    url: https://allineapilates.com
    maxResponseTime: 7000
  - name: Estudio Obliquo
    url: https://estudioobliquo.com
    maxResponseTime: 7000
  - name: Lucas Boh
    url: https://lucasboh.com
    maxResponseTime: 7000
  - name: Survey Platform App
    url: https://survey-platform.lucasboh.com/
  - name: Survey Platform API
    url: https://survey-platform-admin.lucasboh.com/


status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.estudioobliquo.com
  # baseUrl: /upptime
  logoUrl: https://estudioobliquo.com/static/6cb011ed95ee3e854ee4ba4b6ea5136d/1d271/logoColor.webp
  favicon: https://estudioobliquo.com/favicon-32x32.png
  name: Estudio Obliquo Status
  theme: ocean
  introTitle: "Status"
  introMessage: ""
  navbar:
    - title: Netlify Status
      href: https://www.netlifystatus.com/  
    - title: DO Status
      href: https://status.digitalocean.com/
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

workflowSchedule:
  graphs: "0 0 * * *"
  responseTime: "0 23 * * *"
  staticSite: "0 1 * * *"
  summary: "0 0 * * *"
  updateTemplate: "0 0 * * *"
  updates: "0 3 * * *"
  uptime: "*/30 * * * *"

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
