# Change these first
owner: lucasboh # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: Estudio Obliquo
    url: https://estudioobliquo.com
  - name: Livieres Guggiari
    url: https://livieresg.com.py
  - name: Sunshine Lettering
    url: https://sunshineletteringpy.com
  - name: CBVA-APP
    url: https://admin.bomberosasuncion.org/login 
  - name: Estudio TFZ
    url: https://estudiotfz.com
  - name: Allinea Pilates
    url: https://allineapilates.com
  - name: Lucas Boh
    url: https://lucasboh.com

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.estudioobliquo.com
  # baseUrl: /upptime
  logoUrl: https://estudioobliquo.com/static/6cb011ed95ee3e854ee4ba4b6ea5136d/1d271/logoColor.webp
  favicon: https://estudioobliquo.com/favicon-32x32.png
  name: Estudio Obliquo Status
  theme: dark
  introTitle: "Status"
  introMessage: ""
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
